### ISSUE TITLE
Latest update not working

### ISSUE THREAD

**Issue by valinet** [mydongistiny/gnome-terminal-fedora#1]
Hi

I tried using the latest PKGBUILD, yet it fails building gnome-terminal 3.32 for me:

`CC       gnome_terminal_server-terminal-screen.o
terminal-screen.c: In function ‘terminal_screen_class_init’:
terminal-screen.c:515:17: error: ‘VteTerminalClass’ {aka ‘struct _VteTerminalClass’} has no member named ‘shell_precmd’
  515 |   terminal_class->shell_precmd = terminal_screen_shell_precmd;
      |                 ^~
terminal-screen.c:516:17: error: ‘VteTerminalClass’ {aka ‘struct _VteTerminalClass’} has no member named ‘shell_preexec’
  516 |   terminal_class->shell_preexec = terminal_screen_shell_preexec;
      |                 ^~
make[3]: *** [Makefile:1656: gnome_terminal_server-terminal-screen.o] Error 1
make[3]: Leaving directory '/tmp/yaourt-tmp-valentin/aur-gnome-terminal-fedora/src/gnome-terminal-3.32.2/src'
make[2]: *** [Makefile:961: all] Error 2
make[2]: Leaving directory '/tmp/yaourt-tmp-valentin/aur-gnome-terminal-fedora/src/gnome-terminal-3.32.2/src'
make[1]: *** [Makefile:589: all-recursive] Error 1
make[1]: Leaving directory '/tmp/yaourt-tmp-valentin/aur-gnome-terminal-fedora/src/gnome-terminal-3.32.2'
make: *** [Makefile:477: all] Error 2
`

Any idea?

Thanks.

**Comment by valinet** [comment]
I commented out the lines, compiled successfully, yet notifications do not appear. it used to work with 3.30...
